[package]
name = "linera-match-game"
version = "0.1.0"
edition = "2021"

[dependencies]
linera-sdk = "0.15.0"
serde = { version = "1.0.188", features = ["derive"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
